### ISSUE TITLE
issue on assigning  $to ie. phonenumber

### ISSUE THREAD

**Issue by bksbikash** [TheBikramLama/sparrow#2]
i was going through your work , when i use the below condition it sucessfully sends the message or even if i put i single number as $to in my config it works.       
 $sms_message = Sparrow::send('1234567890,'This is message') 
Issue here is i have $phonenumber and i want to pass it here
 $sms_message = Sparrow::send($phonenumber,'This is message') 
even if the number is int/string it doesnot work . 
How can  admin pass different number from database without assigning variable here.

---------------------------------------------------------
issue solved 
it was not the issue i changed the identity to other name thats why message was not sending , identity must be Demo unless it is changed .

**Comment by TheBikramLama** [comment]
Glad it has been solved 😁
